### ISSUE TITLE
rp not ready

### ISSUE THREAD

**Issue by jlai79** [Aymkdn/RibbonPlus#1]
If I use this code the rp.ready function is not always called. Sometimes the new button is added and sometimes not. Any idea how to fix that?

```
var rp = new RibbonPlus();
// make sure the ribbon is ready
rp.ready(function() {
   rp.addButtons("My Toolbar", "My Actions", [
   ...
}
```

**Comment by Aymkdn** [comment]
It's a very old project that I don't use for many years… So it's hard to say.

`rp.ready` is triggered by a native Sharepoint function:
```js
SP.SOD.executeOrDelayUntilScriptLoaded(function () {
      initRibbon();
    }, "sp.ribbon.js");
```

But it may fail.

Can you try the below:
```js
SP.SOD.executeOrDelayUntilEventNotified(function() {
  console.log("ribbon loaded");
}, "sp.scriptloaded-sp.ribbon.js")
```

And:
```js
var rp = new RibbonPlus();
// make sure the ribbon is ready
rp.ready(function() {
  console.log("RibbonPlus Ready")
})
```

To see if the `SP.SOD.executeOrDelayUntilEventNotified` function works better?
